//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36315
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DmsCore.NbsAccounts {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://communicationoffice.nbs.rs", ConfigurationName="NbsAccounts.CompanyAccountXmlServiceSoap")]
    public interface CompanyAccountXmlServiceSoap {
        
        // CODEGEN: Generating message contract since message GetServiceVersionRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetServiceVersion", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetServiceVersionResponse GetServiceVersion(DmsCore.NbsAccounts.GetServiceVersionRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountCountRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountCountResponse GetCompanyAccountCount(DmsCore.NbsAccounts.GetCompanyAccountCountRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountResponse GetCompanyAccount(DmsCore.NbsAccounts.GetCompanyAccountRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountByNationalIdentificationNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountByNationalIdentificationNumber" +
            "", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberResponse GetCompanyAccountByNationalIdentificationNumber(DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountStatusRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountStatusResponse GetCompanyAccountStatus(DmsCore.NbsAccounts.GetCompanyAccountStatusRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountTypeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountType", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountTypeResponse GetCompanyAccountType(DmsCore.NbsAccounts.GetCompanyAccountTypeRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountUpdatedCountRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountUpdatedCount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountResponse GetCompanyAccountUpdatedCount(DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountTopRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountTop", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountTopResponse GetCompanyAccountTop(DmsCore.NbsAccounts.GetCompanyAccountTopRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountUpdatedRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountUpdated", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountUpdatedResponse GetCompanyAccountUpdated(DmsCore.NbsAccounts.GetCompanyAccountUpdatedRequest request);
        
        // CODEGEN: Generating message contract since message GetCompanyAccountOriginByNationalIdNumberRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://communicationoffice.nbs.rs/GetCompanyAccountOriginByNationalIdNumber", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberResponse GetCompanyAccountOriginByNationalIdNumber(DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.36315")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://communicationoffice.nbs.rs")]
    public partial class AuthenticationHeader : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Guid licenceIDField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid LicenceID {
            get {
                return this.licenceIDField;
            }
            set {
                this.licenceIDField = value;
                this.RaisePropertyChanged("LicenceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceVersion", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetServiceVersionRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        public GetServiceVersionRequest() {
        }
        
        public GetServiceVersionRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader) {
            this.AuthenticationHeader = AuthenticationHeader;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetServiceVersionResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetServiceVersionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetServiceVersionResult;
        
        public GetServiceVersionResponse() {
        }
        
        public GetServiceVersionResponse(string GetServiceVersionResult) {
            this.GetServiceVersionResult = GetServiceVersionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountCount", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountCountRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> nationalIdentificationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=1)]
        public string taxIdentificationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> bankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> controlNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=5)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=6)]
        public string city;
        
        public GetCompanyAccountCountRequest() {
        }
        
        public GetCompanyAccountCountRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<long> nationalIdentificationNumber, string taxIdentificationNumber, System.Nullable<long> bankCode, System.Nullable<long> accountNumber, System.Nullable<int> controlNumber, string companyName, string city) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.nationalIdentificationNumber = nationalIdentificationNumber;
            this.taxIdentificationNumber = taxIdentificationNumber;
            this.bankCode = bankCode;
            this.accountNumber = accountNumber;
            this.controlNumber = controlNumber;
            this.companyName = companyName;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountCountResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public long GetCompanyAccountCountResult;
        
        public GetCompanyAccountCountResponse() {
        }
        
        public GetCompanyAccountCountResponse(long GetCompanyAccountCountResult) {
            this.GetCompanyAccountCountResult = GetCompanyAccountCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccount", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> nationalIdentificationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=1)]
        public string taxIdentificationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> bankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> controlNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=5)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=6)]
        public string city;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> startItemNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> endItemNumber;
        
        public GetCompanyAccountRequest() {
        }
        
        public GetCompanyAccountRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<long> nationalIdentificationNumber, string taxIdentificationNumber, System.Nullable<long> bankCode, System.Nullable<long> accountNumber, System.Nullable<int> controlNumber, string companyName, string city, System.Nullable<long> startItemNumber, System.Nullable<long> endItemNumber) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.nationalIdentificationNumber = nationalIdentificationNumber;
            this.taxIdentificationNumber = taxIdentificationNumber;
            this.bankCode = bankCode;
            this.accountNumber = accountNumber;
            this.controlNumber = controlNumber;
            this.companyName = companyName;
            this.city = city;
            this.startItemNumber = startItemNumber;
            this.endItemNumber = endItemNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountResult;
        
        public GetCompanyAccountResponse() {
        }
        
        public GetCompanyAccountResponse(string GetCompanyAccountResult) {
            this.GetCompanyAccountResult = GetCompanyAccountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountByNationalIdentificationNumber", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountByNationalIdentificationNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public long nationalIdentificationNumber;
        
        public GetCompanyAccountByNationalIdentificationNumberRequest() {
        }
        
        public GetCompanyAccountByNationalIdentificationNumberRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, long nationalIdentificationNumber) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.nationalIdentificationNumber = nationalIdentificationNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountByNationalIdentificationNumberResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountByNationalIdentificationNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountByNationalIdentificationNumberResult;
        
        public GetCompanyAccountByNationalIdentificationNumberResponse() {
        }
        
        public GetCompanyAccountByNationalIdentificationNumberResponse(string GetCompanyAccountByNationalIdentificationNumberResult) {
            this.GetCompanyAccountByNationalIdentificationNumberResult = GetCompanyAccountByNationalIdentificationNumberResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountStatus", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountStatusRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> companyAccountStatusID;
        
        public GetCompanyAccountStatusRequest() {
        }
        
        public GetCompanyAccountStatusRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<int> companyAccountStatusID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.companyAccountStatusID = companyAccountStatusID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountStatusResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountStatusResult;
        
        public GetCompanyAccountStatusResponse() {
        }
        
        public GetCompanyAccountStatusResponse(string GetCompanyAccountStatusResult) {
            this.GetCompanyAccountStatusResult = GetCompanyAccountStatusResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountType", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountTypeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> companyAccountTypeID;
        
        public GetCompanyAccountTypeRequest() {
        }
        
        public GetCompanyAccountTypeRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<int> companyAccountTypeID) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.companyAccountTypeID = companyAccountTypeID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountTypeResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountTypeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountTypeResult;
        
        public GetCompanyAccountTypeResponse() {
        }
        
        public GetCompanyAccountTypeResponse(string GetCompanyAccountTypeResult) {
            this.GetCompanyAccountTypeResult = GetCompanyAccountTypeResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountUpdatedCount", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountUpdatedCountRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=1)]
        public string dateTo;
        
        public GetCompanyAccountUpdatedCountRequest() {
        }
        
        public GetCompanyAccountUpdatedCountRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, string dateFrom, string dateTo) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountUpdatedCountResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountUpdatedCountResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public long GetCompanyAccountUpdatedCountResult;
        
        public GetCompanyAccountUpdatedCountResponse() {
        }
        
        public GetCompanyAccountUpdatedCountResponse(long GetCompanyAccountUpdatedCountResult) {
            this.GetCompanyAccountUpdatedCountResult = GetCompanyAccountUpdatedCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountTop", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountTopRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> nationalIdentificationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=1)]
        public string taxIdentificationNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> bankCode;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> accountNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<int> controlNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=5)]
        public string companyName;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=6)]
        public string city;
        
        public GetCompanyAccountTopRequest() {
        }
        
        public GetCompanyAccountTopRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<long> nationalIdentificationNumber, string taxIdentificationNumber, System.Nullable<long> bankCode, System.Nullable<long> accountNumber, System.Nullable<int> controlNumber, string companyName, string city) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.nationalIdentificationNumber = nationalIdentificationNumber;
            this.taxIdentificationNumber = taxIdentificationNumber;
            this.bankCode = bankCode;
            this.accountNumber = accountNumber;
            this.controlNumber = controlNumber;
            this.companyName = companyName;
            this.city = city;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountTopResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountTopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountTopResult;
        
        public GetCompanyAccountTopResponse() {
        }
        
        public GetCompanyAccountTopResponse(string GetCompanyAccountTopResult) {
            this.GetCompanyAccountTopResult = GetCompanyAccountTopResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountUpdated", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountUpdatedRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string dateFrom;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=1)]
        public string dateTo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> startItemNumber;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<long> endItemNumber;
        
        public GetCompanyAccountUpdatedRequest() {
        }
        
        public GetCompanyAccountUpdatedRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, string dateFrom, string dateTo, System.Nullable<long> startItemNumber, System.Nullable<long> endItemNumber) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.dateFrom = dateFrom;
            this.dateTo = dateTo;
            this.startItemNumber = startItemNumber;
            this.endItemNumber = endItemNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountUpdatedResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountUpdatedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountUpdatedResult;
        
        public GetCompanyAccountUpdatedResponse() {
        }
        
        public GetCompanyAccountUpdatedResponse(string GetCompanyAccountUpdatedResult) {
            this.GetCompanyAccountUpdatedResult = GetCompanyAccountUpdatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountOriginByNationalIdNumber", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountOriginByNationalIdNumberRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://communicationoffice.nbs.rs")]
        public DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public long nationalIdentificationNumber;
        
        public GetCompanyAccountOriginByNationalIdNumberRequest() {
        }
        
        public GetCompanyAccountOriginByNationalIdNumberRequest(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, long nationalIdentificationNumber) {
            this.AuthenticationHeader = AuthenticationHeader;
            this.nationalIdentificationNumber = nationalIdentificationNumber;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="GetCompanyAccountOriginByNationalIdNumberResponse", WrapperNamespace="http://communicationoffice.nbs.rs", IsWrapped=true)]
    public partial class GetCompanyAccountOriginByNationalIdNumberResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://communicationoffice.nbs.rs", Order=0)]
        public string GetCompanyAccountOriginByNationalIdNumberResult;
        
        public GetCompanyAccountOriginByNationalIdNumberResponse() {
        }
        
        public GetCompanyAccountOriginByNationalIdNumberResponse(string GetCompanyAccountOriginByNationalIdNumberResult) {
            this.GetCompanyAccountOriginByNationalIdNumberResult = GetCompanyAccountOriginByNationalIdNumberResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CompanyAccountXmlServiceSoapChannel : DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CompanyAccountXmlServiceSoapClient : System.ServiceModel.ClientBase<DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap>, DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap {
        
        public CompanyAccountXmlServiceSoapClient() {
        }
        
        public CompanyAccountXmlServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CompanyAccountXmlServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyAccountXmlServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CompanyAccountXmlServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetServiceVersionResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetServiceVersion(DmsCore.NbsAccounts.GetServiceVersionRequest request) {
            return base.Channel.GetServiceVersion(request);
        }
        
        public string GetServiceVersion(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader) {
            DmsCore.NbsAccounts.GetServiceVersionRequest inValue = new DmsCore.NbsAccounts.GetServiceVersionRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            DmsCore.NbsAccounts.GetServiceVersionResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetServiceVersion(inValue);
            return retVal.GetServiceVersionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountCountResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountCount(DmsCore.NbsAccounts.GetCompanyAccountCountRequest request) {
            return base.Channel.GetCompanyAccountCount(request);
        }
        
        public long GetCompanyAccountCount(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<long> nationalIdentificationNumber, string taxIdentificationNumber, System.Nullable<long> bankCode, System.Nullable<long> accountNumber, System.Nullable<int> controlNumber, string companyName, string city) {
            DmsCore.NbsAccounts.GetCompanyAccountCountRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountCountRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.nationalIdentificationNumber = nationalIdentificationNumber;
            inValue.taxIdentificationNumber = taxIdentificationNumber;
            inValue.bankCode = bankCode;
            inValue.accountNumber = accountNumber;
            inValue.controlNumber = controlNumber;
            inValue.companyName = companyName;
            inValue.city = city;
            DmsCore.NbsAccounts.GetCompanyAccountCountResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountCount(inValue);
            return retVal.GetCompanyAccountCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccount(DmsCore.NbsAccounts.GetCompanyAccountRequest request) {
            return base.Channel.GetCompanyAccount(request);
        }
        
        public string GetCompanyAccount(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<long> nationalIdentificationNumber, string taxIdentificationNumber, System.Nullable<long> bankCode, System.Nullable<long> accountNumber, System.Nullable<int> controlNumber, string companyName, string city, System.Nullable<long> startItemNumber, System.Nullable<long> endItemNumber) {
            DmsCore.NbsAccounts.GetCompanyAccountRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.nationalIdentificationNumber = nationalIdentificationNumber;
            inValue.taxIdentificationNumber = taxIdentificationNumber;
            inValue.bankCode = bankCode;
            inValue.accountNumber = accountNumber;
            inValue.controlNumber = controlNumber;
            inValue.companyName = companyName;
            inValue.city = city;
            inValue.startItemNumber = startItemNumber;
            inValue.endItemNumber = endItemNumber;
            DmsCore.NbsAccounts.GetCompanyAccountResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccount(inValue);
            return retVal.GetCompanyAccountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountByNationalIdentificationNumber(DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberRequest request) {
            return base.Channel.GetCompanyAccountByNationalIdentificationNumber(request);
        }
        
        public string GetCompanyAccountByNationalIdentificationNumber(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, long nationalIdentificationNumber) {
            DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.nationalIdentificationNumber = nationalIdentificationNumber;
            DmsCore.NbsAccounts.GetCompanyAccountByNationalIdentificationNumberResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountByNationalIdentificationNumber(inValue);
            return retVal.GetCompanyAccountByNationalIdentificationNumberResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountStatusResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountStatus(DmsCore.NbsAccounts.GetCompanyAccountStatusRequest request) {
            return base.Channel.GetCompanyAccountStatus(request);
        }
        
        public string GetCompanyAccountStatus(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<int> companyAccountStatusID) {
            DmsCore.NbsAccounts.GetCompanyAccountStatusRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountStatusRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.companyAccountStatusID = companyAccountStatusID;
            DmsCore.NbsAccounts.GetCompanyAccountStatusResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountStatus(inValue);
            return retVal.GetCompanyAccountStatusResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountTypeResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountType(DmsCore.NbsAccounts.GetCompanyAccountTypeRequest request) {
            return base.Channel.GetCompanyAccountType(request);
        }
        
        public string GetCompanyAccountType(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<int> companyAccountTypeID) {
            DmsCore.NbsAccounts.GetCompanyAccountTypeRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountTypeRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.companyAccountTypeID = companyAccountTypeID;
            DmsCore.NbsAccounts.GetCompanyAccountTypeResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountType(inValue);
            return retVal.GetCompanyAccountTypeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountUpdatedCount(DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountRequest request) {
            return base.Channel.GetCompanyAccountUpdatedCount(request);
        }
        
        public long GetCompanyAccountUpdatedCount(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, string dateFrom, string dateTo) {
            DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.dateFrom = dateFrom;
            inValue.dateTo = dateTo;
            DmsCore.NbsAccounts.GetCompanyAccountUpdatedCountResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountUpdatedCount(inValue);
            return retVal.GetCompanyAccountUpdatedCountResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountTopResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountTop(DmsCore.NbsAccounts.GetCompanyAccountTopRequest request) {
            return base.Channel.GetCompanyAccountTop(request);
        }
        
        public string GetCompanyAccountTop(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, System.Nullable<long> nationalIdentificationNumber, string taxIdentificationNumber, System.Nullable<long> bankCode, System.Nullable<long> accountNumber, System.Nullable<int> controlNumber, string companyName, string city) {
            DmsCore.NbsAccounts.GetCompanyAccountTopRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountTopRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.nationalIdentificationNumber = nationalIdentificationNumber;
            inValue.taxIdentificationNumber = taxIdentificationNumber;
            inValue.bankCode = bankCode;
            inValue.accountNumber = accountNumber;
            inValue.controlNumber = controlNumber;
            inValue.companyName = companyName;
            inValue.city = city;
            DmsCore.NbsAccounts.GetCompanyAccountTopResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountTop(inValue);
            return retVal.GetCompanyAccountTopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountUpdatedResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountUpdated(DmsCore.NbsAccounts.GetCompanyAccountUpdatedRequest request) {
            return base.Channel.GetCompanyAccountUpdated(request);
        }
        
        public string GetCompanyAccountUpdated(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, string dateFrom, string dateTo, System.Nullable<long> startItemNumber, System.Nullable<long> endItemNumber) {
            DmsCore.NbsAccounts.GetCompanyAccountUpdatedRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountUpdatedRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.dateFrom = dateFrom;
            inValue.dateTo = dateTo;
            inValue.startItemNumber = startItemNumber;
            inValue.endItemNumber = endItemNumber;
            DmsCore.NbsAccounts.GetCompanyAccountUpdatedResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountUpdated(inValue);
            return retVal.GetCompanyAccountUpdatedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberResponse DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap.GetCompanyAccountOriginByNationalIdNumber(DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberRequest request) {
            return base.Channel.GetCompanyAccountOriginByNationalIdNumber(request);
        }
        
        public string GetCompanyAccountOriginByNationalIdNumber(DmsCore.NbsAccounts.AuthenticationHeader AuthenticationHeader, long nationalIdentificationNumber) {
            DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberRequest inValue = new DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberRequest();
            inValue.AuthenticationHeader = AuthenticationHeader;
            inValue.nationalIdentificationNumber = nationalIdentificationNumber;
            DmsCore.NbsAccounts.GetCompanyAccountOriginByNationalIdNumberResponse retVal = ((DmsCore.NbsAccounts.CompanyAccountXmlServiceSoap)(this)).GetCompanyAccountOriginByNationalIdNumber(inValue);
            return retVal.GetCompanyAccountOriginByNationalIdNumberResult;
        }
    }
}
